name: Release
on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
        - name: checkout repository
          uses: actions/checkout@v4

        - name: validate gradle wrapper
          uses: gradle/actions/wrapper-validation@v4

        - name: setup jdk
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'microsoft'

        - name: make gradle wrapper executable
          run: chmod +x ./gradlew

        - name: build
          run: ./gradlew build

        - name: Publish to CurseForge
          uses: Kir-Antipov/mc-publish@v3.3
          with:
            curseforge-id: 1345462
            curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}



